export enum SdkErrorCode {
  // Validation
  INVALID_ADDRESS = "INVALID_ADDRESS",
  INVALID_AMOUNT = "INVALID_AMOUNT",
  INVALID_METADATA_URI = "INVALID_METADATA_URI",
  INVALID_PRICE = "INVALID_PRICE",
  INVALID_FEE = "INVALID_FEE",
  SIGNER_REQUIRED = "SIGNER_REQUIRED",
  CHAIN_NOT_SUPPORTED = "CHAIN_NOT_SUPPORTED",

  // Contract reverts
  PLAYER_ALREADY_REGISTERED = "PLAYER_ALREADY_REGISTERED",
  PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND",
  CLUB_ALREADY_REGISTERED = "CLUB_ALREADY_REGISTERED",
  CLUB_NOT_FOUND = "CLUB_NOT_FOUND",
  LISTING_NOT_FOUND = "LISTING_NOT_FOUND",
  OFFER_NOT_FOUND = "OFFER_NOT_FOUND",
  AGREEMENT_NOT_FOUND = "AGREEMENT_NOT_FOUND",
  DEPOSIT_NOT_FOUND = "DEPOSIT_NOT_FOUND",
  UNAUTHORIZED = "UNAUTHORIZED",
  INVALID_STATE = "INVALID_STATE",
  TOKEN_ALREADY_SUPPORTED = "TOKEN_ALREADY_SUPPORTED",
  TOKEN_NOT_SUPPORTED = "TOKEN_NOT_SUPPORTED",
  INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",
  PROTOCOL_PAUSED = "PROTOCOL_PAUSED",

  // Provider
  CONNECTION_FAILED = "CONNECTION_FAILED",
  CHAIN_MISMATCH = "CHAIN_MISMATCH",
  REQUEST_TIMEOUT = "REQUEST_TIMEOUT",

  // Transaction
  GAS_ESTIMATION_FAILED = "GAS_ESTIMATION_FAILED",
  SUBMISSION_FAILED = "SUBMISSION_FAILED",
  CONFIRMATION_TIMEOUT = "CONFIRMATION_TIMEOUT",
  REPLACEMENT_UNDERPRICED = "REPLACEMENT_UNDERPRICED",

  // Unknown
  UNKNOWN = "UNKNOWN",
}
